config/routes.rb
Rails.application.routes.draw do
  get 'groups/index'

  root 'feed#index'

  resources :feed
  resources :groups

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.photo_50 = auth["extra"]['raw_info']["photo_50"]
      user.photo_orig = auth["info"]['image']
      user.url = auth['info']['urls']['Vkontakte']      
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    if session[:token]
      @vk = VkontakteApi::Client.new(session[:token])
      @photos = @vk.photos.get_all(owner_id: '-91016989', extended: 0, count: 40)[1..-1]
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :json

  def index
    if session[:token]
      @vk = VkontakteApi::Client.new(session[:token])
      @photos = @vk.groups.get(
              user_id: @vk.user_id,
              extended: 1,
              filter: [:groups, :publics],
              count: 20
            )[1..-1]
      respond_with @photos
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:token] = auth['credentials']['token']
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    session[:token] = nil
    redirect_to root_url, notice: 'Signed out!'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/feed/index.html.slim
= react_component('GroupBox', {url: groups_path(format: :json)})
.panel
  - if @photos
    ul#feed.clearing-thumbs.small-block-grid-1.medium-block-grid-4.large-block-grid-6 data-clearing=''
      - @photos.each do |photo|
        li
          = link_to photo.src_big
            = image_tag photo.src_big, width: 200, height: 200
  - else
    ' need to authorize

app/views/groups/index.html.slim
h1 Groups#index
p Find me in app/views/groups/index.html.slim

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.min.js"
    = csrf_meta_tag

  body
    nav.top-bar data-topbar='' role='navigation'
      ul.title-area
        li.name
          h1
            = link_to 'pik4a', root_path
      section.top-bar-section
        ul.right
          - if current_user
            li
              = image_tag current_user.photo_50, height: 45, width: 45
            li
              = link_to current_user.url, target: :blank do
                = current_user.name
            li.divider
            li.has-form.show-for-large-up
              = link_to 'Sign out', signout_path, class: 'button'
          - else
            li.has-form.show-for-large-up
              = link_to "Sign In", "auth/vkontakte", class: 'button'

    == yield